#spring:
#  datasource:
#    #   jdbc:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.0.104:3307/ns
#    username: root
#    password: 123456
server:
  port: 9999
spring:
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: center
    password: 123qwe
