#spring:
#  datasource:
#    #   jdbc:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.0.104:3307/ns
#    username: root
#    password: 123456
server:
  port: 9999
spring:
  data:
    mongodb:
      host: localhost
      database: ns-limeihua
      port: 47017
      username: admin
      password: admin
      authentication-database: admin
  redis:
    port: 6379
    host: localhost
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
