#spring:
#  datasource:
#    #   jdbc:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.0.104:3307/ns
#    username: root
#    password: 123456

spring:
  redis:
    port: 6379
    host: localhost
